<?php

namespace App\Http\Controllers;

use App\Services\ProductService;
use Illuminate\Http\Request;

class ProductController extends Controller
{
    public function index(ProductService $productService)
    {
        $products = $productService->getProducts();
        return view('pages.products.index' , compact('products'));
    }

    public function temp()
    {
        $data = json_decode('
        {
    "queue_key": "order-created",
    "tenant_id": "e2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46",
    "id": 25742,
    "tracking_code": "SHP-5275328226",
    "payment_method": null,
    "total_weight": 0,
    "user_id": 26541,
    "address_id": null,
    "shipping_method": null,
    "shipping_price": 0,
    "shipping_tracking_code": null,
    "coupon_id": null,
    "coupon_price": null,
    "discount": "0",
    "vat_price": "0",
    "package_price": "0",
    "total": "719750000",
    "items_payable": 719750000,
    "payable": "719750000",
    "payed": "719750000",
    "payment_status": 1,
    "status": 1,
    "status_text": "سفارش جدید",
    "full_name": null,
    "province_id": null,
    "channel_id": 2,
    "channel_name": "صندوق فروش",
    "province": null,
    "city_id": null,
    "city": null,
    "address": null,
    "postal_code": null,
    "mobile": null,
    "email": null,
    "tel": null,
    "receipt_file": null,
    "description": null,
    "created_at": "2025-11-24T00:28:56.000000Z",
    "payment_type": 4,
    "payment_type_text": "پرداخت نقدی",
    "cart_id": null,
    "order_reason_id": null,
    "link": "eW26g",
    "link_id": null,
    "transaction_id": null,
    "payment_type_description": null,
    "read_at": "2025-11-24 03:58:56",
    "order_reason_text": null,
    "creator_id": 26490,
    "creator_full_name": " ",
    "creator_mobile": "09134549085",
    "parent_id": null,
    "comment": null,
    "shipping_price_id": null,
    "shipping_price_alias_name": null,
    "total_tax": 0,
    "tenant_mobile": null,
    "tenant_description": null,
    "tenant_name": null,
    "tenant_pi_description": null,
    "tenant_order_description": null,
    "tenant_registration": null,
    "tenant_postal_code": null,
    "tenant_address": null,
    "tenant_tell": null,
    "shipping_payable": 0,
    "shortner_link": "https://taam.io/eW26g",
    "has_wallet_paid": null,
    "wallet_paid": null,
    "monitor_id": null,
    "referer": null,
    "hasOffers": false,
    "receipt_file_url": null,
    "items": [
        {
            "id": 56160,
            "order_id": 25742,
            "user_id": 26490,
            "product_id": 24408,
            "unit_id": 1,
            "price_id": 210611,
            "count": 2,
            "coefficient": 1,
            "price": 357000000,
            "weight": 0,
            "discount": 0,
            "payable_price": 357000000,
            "product_name": "گوشی موبایل اپل iPhone 17 Pro Max ZA/A Not Active (تک سیمکارت + eSIM) ظرفیت 1 ترابایت و رم 12 گیگابایت",
            "is_decimal_stock_allowed": 0,
            "combination_text": "نارنچی",
            "code": null,
            "barcode": null,
            "type_id": 0,
            "created_at": "2025-11-23T20:58:54.000000Z",
            "is_gift": 0,
            "options": null,
            "tax_value": null,
            "tax_id": 1,
            "net_price": 357000000,
            "purchase_price": null,
            "barcode_taamito": null,
            "title": null,
            "unit_name": "تعداد",
            "unit_symbol": "عدد",
            "total": 714000000,
            "hasOffers": false,
            "count_coefficient": 2,
            "coefficiented_price": 357000000,
            "coefficiented_payable_price": 357000000,
            "total_payable": 714000000,
            "total_discount": 0,
            "total_tax_value": 0,
            "return_invoice_item_count": 0,
            "product": {
                "id": 24408,
                "tenant_id": "e2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46",
                "type_id": 1,
                "old_id": null,
                "category_id": 5370,
                "brand_id": null,
                "thumbnail_file_id": 131319,
                "unit_id": 1,
                "file_id": null,
                "name": "گوشی موبایل اپل iPhone 17 Pro Max ZA/A Not Active (تک سیمکارت + eSIM) ظرفیت 1 ترابایت و رم 12 گیگابایت",
                "second_name": null,
                "is_saleable": 1,
                "min_order_quantity": 1,
                "max_order_quantity": 10,
                "short_description": "<p class=\"ql-align-justify\">گوشی&nbsp;<span style=\"color: rgb(0, 0, 0);\">آیفون 17 پرو مکس</span>&nbsp;جدیدترین پرچمدار اپل در سال 2025 است که با ترکیب سخت‌افزار قدرتمند، طراحی لوکس و امکانات نرم‌افزاری پیشرفته، تجربه‌ای فراتر از انتظار را برای کاربران حرفه‌ای فراهم می‌سازد.</p>",
                "description": "<p class=\"ql-align-justify\">گوشی&nbsp;<span style=\"color: rgb(0, 0, 0);\">آیفون 17 پرو مکس</span>&nbsp;جدیدترین پرچمدار اپل در سال 2025 است که با ترکیب سخت‌افزار قدرتمند، طراحی لوکس و امکانات نرم‌افزاری پیشرفته، تجربه‌ای فراتر از انتظار را برای کاربران حرفه‌ای فراهم می‌سازد. این مدل با بدنه‌ای از جنس شیشه مقاوم (Corning) و فریم آلومینیومی یکپارچه، طراحی ظریف و در عین حال مقاومی دارد و همچنان با گواهی IP68 در برابر آب و گردوغبار محافظت می‌شود.</p>",
                "price": 357000000,
                "weight": null,
                "purchase_price": 0,
                "visit_count": 2,
                "sale_count": 6,
                "favorite_count": 0,
                "rate": 0,
                "stock": -6,
                "coefficient": 1,
                "is_recommended": 0,
                "status": 1,
                "stock_alarm": null,
                "apply_inventory": 1,
                "continue_sell": 1,
                "apply_tax": 0,
                "created_at": "2025-11-23T10:24:23.000000Z",
                "updated_at": "2025-11-24T00:28:56.000000Z",
                "deleted_at": null,
                "code": null,
                "barcode": null,
                "instagram_id": null,
                "width": null,
                "height": null,
                "length": null,
                "formula": null,
                "has_formula": 0,
                "order": 2,
                "is_preview": 0,
                "creator_id": 26490,
                "creator_full_name": " ",
                "creator_mobile": "09134549085",
                "local_id": 2,
                "barcode_taamito": null,
                "tax_id": 1,
                "stock_incoming": 0,
                "stock_unavailable": 0,
                "stock_reserve": 0,
                "is_decimal_stock_allowed": 0,
                "avalibility": false,
                "coefficiented_price": 357000000,
                "thumbnail_url": "https://tsd-taamito-tenants.s3.ir-thr-at1.arvanstorage.ir/tenants/tenante2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46/products/176389339142848.jpeg",
                "slug": "گوشی-موبایل-اپل-iphone-17-pro-max-zaa-not-active-تک-سیمکارت-esim-ظرفیت-1-ترابایت-و-رم-12-گیگابایت",
                "thumbnail": {
                    "id": 131319,
                    "tenant_id": "e2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46",
                    "file_url": "products/176389339142848.jpeg",
                    "parent_id": 0,
                    "mime_type": "image/jpeg",
                    "size": "74365",
                    "file_server": "local",
                    "created_at": "2025-11-23T10:23:11.000000Z",
                    "deleted_at": null,
                    "full_url": "https://tsd-taamito-tenants.s3.ir-thr-at1.arvanstorage.ir/tenants/tenante2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46/products/176389339142848.jpeg",
                    "small_full_url": "https://tsd-taamito-tenants.s3.ir-thr-at1.arvanstorage.ir/tenants/tenante2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46/products/176389339142848-small.jpeg",
                    "thumbnail_full_url": "https://tsd-taamito-tenants.s3.ir-thr-at1.arvanstorage.ir/tenants/tenante2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46/products/176389339142848-small.jpeg",
                    "is_image": true
                }
            }
        },
        {
            "id": 56161,
            "order_id": 25742,
            "user_id": 26490,
            "product_id": 24407,
            "unit_id": 1,
            "price_id": 210608,
            "count": 1,
            "coefficient": 1,
            "price": 5750000,
            "weight": 0,
            "discount": 0,
            "payable_price": 5750000,
            "product_name": "دسته بازی سونی پلی استیشن 5 مدل Dualsence 30th Anniversary - Limited Edition - نسخه محدود",
            "is_decimal_stock_allowed": 0,
            "combination_text": "قرمز",
            "code": null,
            "barcode": null,
            "type_id": 0,
            "created_at": "2025-11-23T20:58:54.000000Z",
            "is_gift": 0,
            "options": null,
            "tax_value": null,
            "tax_id": 1,
            "net_price": 5750000,
            "purchase_price": null,
            "barcode_taamito": null,
            "title": null,
            "unit_name": "تعداد",
            "unit_symbol": "عدد",
            "total": 5750000,
            "hasOffers": false,
            "count_coefficient": 1,
            "coefficiented_price": 5750000,
            "coefficiented_payable_price": 5750000,
            "total_payable": 5750000,
            "total_discount": 0,
            "total_tax_value": 0,
            "return_invoice_item_count": 0,
            "product": {
                "id": 24407,
                "tenant_id": "e2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46",
                "type_id": 1,
                "old_id": null,
                "category_id": 5369,
                "brand_id": null,
                "thumbnail_file_id": null,
                "unit_id": 1,
                "file_id": null,
                "name": "دسته بازی سونی پلی استیشن 5 مدل Dualsence 30th Anniversary - Limited Edition - نسخه محدود",
                "second_name": null,
                "is_saleable": 1,
                "min_order_quantity": 1,
                "max_order_quantity": 10,
                "short_description": "<p><span style=\"color: oklch(0.373 0.034 259.733);\">کنترلر&nbsp;</span><span style=\"color: rgb(0, 0, 0);\">DualSense 30th Anniversary - Limited Edition</span><span style=\"color: oklch(0.373 0.034 259.733);\">&nbsp;از سری محصولات ویژه‌ی سونی است که به مناسبت&nbsp;</span><span style=\"color: rgb(0, 0, 0);\">30 سالگی برند پلی‌استیشن</span><span style=\"color: oklch(0.373 0.034 259.733);\">&nbsp;عرضه شده است.</span></p>",
                "description": "<p><span style=\"color: oklch(0.373 0.034 259.733);\">کنترلر&nbsp;</span><span style=\"color: rgb(0, 0, 0);\">DualSense 30th Anniversary - Limited Edition</span><span style=\"color: oklch(0.373 0.034 259.733);\">&nbsp;از سری محصولات ویژه‌ی سونی است که به مناسبت&nbsp;</span><span style=\"color: rgb(0, 0, 0);\">30 سالگی برند پلی‌استیشن</span><span style=\"color: oklch(0.373 0.034 259.733);\">&nbsp;عرضه شده است. این نسخه‌ی محدود با طراحی نمادین، رنگ نوستالژیک و امکانات کامل، یادآور خاطرات نسل‌های اولیه کنسول پلی‌استیشن برای علاقه‌مندان و کلکسیون‌داران است.</span></p>",
                "price": 5750000,
                "weight": null,
                "purchase_price": 0,
                "visit_count": 3,
                "sale_count": 4,
                "favorite_count": 0,
                "rate": 0,
                "stock": 1,
                "coefficient": 1,
                "is_recommended": 0,
                "status": 1,
                "stock_alarm": null,
                "apply_inventory": 1,
                "continue_sell": 1,
                "apply_tax": 0,
                "created_at": "2025-11-23T10:21:20.000000Z",
                "updated_at": "2025-11-24T00:28:56.000000Z",
                "deleted_at": null,
                "code": null,
                "barcode": null,
                "instagram_id": null,
                "width": null,
                "height": null,
                "length": null,
                "formula": null,
                "has_formula": 0,
                "order": 1,
                "is_preview": 0,
                "creator_id": 26490,
                "creator_full_name": " ",
                "creator_mobile": "09134549085",
                "local_id": 1,
                "barcode_taamito": null,
                "tax_id": 1,
                "stock_incoming": 0,
                "stock_unavailable": 0,
                "stock_reserve": 0,
                "is_decimal_stock_allowed": 0,
                "avalibility": true,
                "coefficiented_price": 5750000,
                "thumbnail_url": "http://jssor.taamito.com/api/uploads/defaults/default.jpg",
                "slug": "دسته-بازی-سونی-پلی-استیشن-5-مدل-dualsence-30th-anniversary-limited-edition-نسخه-محدود",
                "thumbnail": null
            }
        }
    ],
    "channel": {
        "id": 2,
        "name": "صندوق فروش",
        "service": "-",
        "meta": null,
        "created_at": null,
        "status": 1
    },
    "paymethod": null,
    "tenant": {
        "id": "e2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46",
        "name": null,
        "family": null,
        "site_name": null,
        "mobile": "09134549085",
        "created_at": "2025-11-23T10:13:49.000000Z",
        "updated_at": "2025-11-23T10:13:49.000000Z",
        "data": null,
        "user_id": 26490,
        "tenant_step": 3,
        "site_domain": "jssor",
        "status": 1,
        "invitation_code": null,
        "last_login_at": null,
        "plan_id": 3,
        "plan_expire_at": "2025-11-29T20:30:00.000000Z",
        "fee_percentage": 5,
        "pkg_id": 0,
        "is_trial": true
    },
    "user": {
        "id": 26541,
        "tenant_id": "e2e5cb89-bf46-4cfd-b149-7fe9ecfe9b46",
        "name": "علی",
        "family": null,
        "invition_code": null,
        "credit": "0",
        "mobile": "09131111111",
        "username": null,
        "email": "",
        "ssn": null,
        "sex": null,
        "birth_at": null,
        "shaba": null,
        "bank_account": null,
        "avatar": null,
        "newsletter": 0,
        "promotions": 0,
        "status": 0,
        "type": 1,
        "force_password_change": 0,
        "is_administrator": 0,
        "email_verify_token": null,
        "mobile_verify_token": null,
        "mobile_verification_expire_at": null,
        "email_verified_at": null,
        "mobile_verified_at": null,
        "channel_id": 2,
        "created_at": "2025-11-23T22:38:13.000000Z",
        "updated_at": "2025-11-23T22:38:13.000000Z",
        "deleted_at": null,
        "instagram_id": "",
        "instagram_username": "",
        "last_login_at": null,
        "marriage_at": null,
        "code": null,
        "category_id": null,
        "is_enable_password": 0,
        "form_id": null,
        "creator_id": 26490,
        "reputation": 0,
        "restriction_status": "full_access",
        "full_name": "علی ",
        "avatar_url": "http://jssor.taamito.com/api/uploads/defaults/default.jpg",
        "is_complete": false,
        "has_password": false,
        "instagram_url": "https://www.instagram.com/"
    }
}
        ' , true);
        return view('pages.orders.inc.invoice-pdf', [
            'font_family' => 'shabnam',
            'direction' => 'rtl',
            'text_align' => 'right',
            'order' => $data,
        ]);
    }
}
